public class EEC_LicenseAttachmentsExtension extends BaseAttachmentsExtension implements AttachActionInterface {

  public EEC_LicenseAttachmentsExtension(ApexPages.StandardController std) {
    super(std);
  }

  /**
   * getCtrlInstance
   * 
   * This function will return an instance of this controller with interface reference.
   * @author Darkis
   * @return EEC_LicenseAttachmentsExtension
   */
  public EEC_LicenseAttachmentsExtension getCtrlInstance() {
    return this;
  }
}